// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeverGrpc_NHibernate.Data;

#nullable disable

namespace SeverGrpc_NHibernate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250324071656_seed data")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeverGrpc_NHibernate.Model.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Math 101",
                            Subject = "Mathematics",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Math 102",
                            Subject = "Mathematics",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Math 103",
                            Subject = "Mathematics",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Physics 201",
                            Subject = "Physics",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Physics 202",
                            Subject = "Physics",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Physics 203",
                            Subject = "Physics",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chemistry 301",
                            Subject = "Chemistry",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Chemistry 302",
                            Subject = "Chemistry",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Chemistry 303",
                            Subject = "Chemistry",
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("SeverGrpc_NHibernate.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("SeverGrpc_NHibernate.Model.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teacher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1980, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1985, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1975, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Robert Johnson"
                        });
                });

            modelBuilder.Entity("SeverGrpc_NHibernate.Model.Class", b =>
                {
                    b.HasOne("SeverGrpc_NHibernate.Model.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SeverGrpc_NHibernate.Model.Student", b =>
                {
                    b.HasOne("SeverGrpc_NHibernate.Model.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SeverGrpc_NHibernate.Model.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SeverGrpc_NHibernate.Model.Teacher", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
